using System;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.IO;
using System.Windows;
using Microsoft.Toolkit.Mvvm.ComponentModel;
using WahooFitToGarmin_Desktop.Contracts.Services;
using WahooFitToGarmin_Desktop.Helpers;

namespace WahooFitToGarmin_Desktop.ViewModels
{
    public class MainViewModel : ObservableObject
    {
        private readonly IToastNotificationsService _toastNotificationsService;
        private string _wahooFolder;
        private string _garminLogin;
        private string _garminPwd;

        public ObservableCollection<LogEntry> LogEntries { get; set; }

        public MainViewModel(IToastNotificationsService toastNotificationsService)
        {
            _toastNotificationsService = toastNotificationsService;
            LogEntries = new ObservableCollection<LogEntry> { new LogEntry("Starting .......") };
            DumpSettings();

            if (Directory.Exists(_wahooFolder) && !string.IsNullOrEmpty(_garminLogin) && !string.IsNullOrEmpty(_garminPwd))
            {
                var fw = new FileSystemWatcher
                {
                    Filter = "*.fit",
                    Path = _wahooFolder,
                    EnableRaisingEvents = true,
                    IncludeSubdirectories = false
                };
                fw.Created += FileIsComing;
            }
            else
            {
                Log("Please feel correctly yours app settings in settings screen and restart the application to apply them");
            }

        }

        private void FileIsComing(object sender, FileSystemEventArgs e)
        {
            Log($"A new file is coming => {e.Name}");
            _toastNotificationsService.ShowSimpleToastNotification("A new file is coming", e.Name);
            var res = Run(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "garmin-uploader", "cli.py"), $"-u \"{_garminLogin}\" -p \"{_garminPwd}\" \"{e.FullPath}\" -v 1");

            Log($" Garmin_uploader execution result ==> \r\n {res}");

            if (res.Contains("Uploaded activity") || res.Contains("Activity already uploaded"))
                System.IO.File.Delete(e.FullPath);

            Log("-------------------------------------------------------------------------------");
        }

        private void DumpSettings()
        {
            _wahooFolder = App.Current.Properties["WahooDropBoxFolder"].ToString();
            if (string.IsNullOrEmpty(_wahooFolder))
                Log("Please select folder to watch for in settings");

            Log($"Wahoo folder to watch for : {_wahooFolder}");

            _garminLogin = App.Current.Properties["GarminLogin"].ToString();
            _garminPwd = App.Current.Properties["GarminPwd"].ToString();
            if (string.IsNullOrEmpty(_garminLogin) || string.IsNullOrEmpty(_garminPwd))
                Log("Please enter your Garmin login and password in settings");
        }

        private void Log(string message)
        {
            Application.Current.Dispatcher.Invoke(
                () => { LogEntries.Add(new LogEntry(message)); });
        }

        private string Run(string cmd, string args)
        {
            var start = new ProcessStartInfo
            {
                FileName = "python3",
                Arguments = $"{cmd} {args}",
                UseShellExecute = false, // Do not use OS shell
                CreateNoWindow = true, // We don't need new window
                RedirectStandardOutput = true, // Any output, generated by application will be redirected back
                RedirectStandardError = true // Any error in standard output will be redirected back (for example exceptions)
            };
            using Process process = Process.Start(start);
            using StreamReader reader = process.StandardOutput;
            string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
            string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")


            return stderr + " " + result;

        }
    }
}
